[mgr]

keymap = [
	{ on = "<Esc>", run = "escape",             desc = "Exit visual mode, clear selection, or cancel search" },
	{ on = "q",     run = "quit",               desc = "Quit the process" },
	{ on = "<C-c>", run = "close",              desc = "Close the current tab, or quit if it's last" },

	# Hopping
	{ on = "k", run = "arrow prev", desc = "Previous file" },
	{ on = "j", run = "arrow next", desc = "Next file" },

	{ on = "<C-u>", run = "arrow -50%",  desc = "Move cursor up half page" },
	{ on = "<C-d>", run = "arrow 50%",   desc = "Move cursor down half page" },

	{ on = [ "g", "g" ], run = "arrow top", desc = "Go to top" },
	{ on = "G",          run = "arrow bot", desc = "Go to bottom" },

	# Navigation
	{ on = "h", run = "leave", desc = "Back to the parent directory" },
	{ on = "l", run = "enter", desc = "Enter the child directory" },

	# Toggle
	{ on = [ "<Space>", "b"], run = [ "toggle", "arrow 1" ], desc = "Toggle selection" },
	{ on = "<C-a>",   run = "toggle_all --state=on", desc = "Select all" },
	{ on = "<C-r>",   run = "toggle_all",            desc = "Invert selection" },

	# Visual mode
	{ on = "<C-v>", run = "visual_mode",         desc = "Enter visual mode (selection mode)" },
	{ on = "<C-V>", run = "visual_mode --unset", desc = "Enter visual mode (unset mode)" },

	# Spotting
	{ on = "<Tab>", run = "spot", desc = "Spot hovered file" },

	# Operation

	{ on = "<Enter>",   run = "open",                        desc = "Open" },
	{ on = "<C-Enter>", run = "open --interactive",          desc = "Open interactively" },
	{ on = "y",         run = "yank",                        desc = "Yank (copy)" },
	{ on = "x",         run = "yank --cut",                  desc = "Yank (cut)" },
	{ on = "p",         run = "paste",                       desc = "Paste yanked" },
	{ on = "P",         run = "paste --force",               desc = "Paste yanked (overwrite)" },
	{ on = "d",         run = "remove",                      desc = "Trash selected" },
	{ on = "D",         run = "remove --permanently",        desc = "Permanently delete selected" },
	{ on = "%",         run = "create",                      desc = "Create a file (ends with / for directories)" },
	{ on = "C-r",         run = "rename --cursor=before_ext",  desc = "Rename" },
	{ on = ":",         run = "shell --block --interactive", desc = "Shell command" },
	{ on = ".",         run = "hidden toggle",               desc = "Toggle hidden" },
	{ on = [ "<Space>", "<Space>" ],         run = "search --via=fd",             desc = "Search files" },
	{ on = [ "<Space>", "d"],         run = "search --via=rg",             desc = "Search filecontent" },

	# Copy
	{ on = [ "c", "c" ], run = "copy path",             desc = "Copy file path" },
	{ on = [ "c", "d" ], run = "copy dirname",          desc = "Copy directory path" },
	{ on = [ "c", "f" ], run = "copy filename",         desc = "Copy filename" },

	# Filter
	{ on = "f", run = "filter --smart", desc = "Filter files" },

	# Find
	{ on = "/", run = "find --smart",            desc = "Find next" },
	{ on = "n", run = "find_arrow",              desc = "Next" },
	{ on = "N", run = "find_arrow --previous",   desc = "Previous" },

	# Sorting
	{ on = [ ",", "m" ], run = [ "sort mtime --reverse=no", "linemode mtime" ],  desc = "Sort by modified time" },
	{ on = [ ",", "M" ], run = [ "sort mtime --reverse=yes", "linemode mtime" ], desc = "Sort by modified time (reverse)" },
	{ on = [ ",", "b" ], run = [ "sort btime --reverse=no", "linemode btime" ],  desc = "Sort by birth time" },
	{ on = [ ",", "B" ], run = [ "sort btime --reverse=yes", "linemode btime" ], desc = "Sort by birth time (reverse)" },
	{ on = [ ",", "e" ], run = "sort extension --reverse=no",                    desc = "Sort by extension" },
	{ on = [ ",", "E" ], run = "sort extension --reverse=yes",                   desc = "Sort by extension (reverse)" },
	{ on = [ ",", "a" ], run = "sort alphabetical --reverse=no",                 desc = "Sort alphabetically" },
	{ on = [ ",", "A" ], run = "sort alphabetical --reverse=yes",                desc = "Sort alphabetically (reverse)" },
	{ on = [ ",", "n" ], run = "sort natural --reverse=no",                      desc = "Sort naturally" },
	{ on = [ ",", "N" ], run = "sort natural --reverse=yes",                     desc = "Sort naturally (reverse)" },
	{ on = [ ",", "s" ], run = [ "sort size --reverse=no", "linemode size" ],    desc = "Sort by size" },
	{ on = [ ",", "S" ], run = [ "sort size --reverse=yes", "linemode size" ],   desc = "Sort by size (reverse)" },
	{ on = [ ",", "r" ], run = "sort random --reverse=no",                       desc = "Sort randomly" },

	# Tabs
	{ on = "t", run = "tab_create --current", desc = "Create a new tab with CWD" },

	{ on = "1", run = "tab_switch 0", desc = "Switch to first tab" },
	{ on = "2", run = "tab_switch 1", desc = "Switch to second tab" },
	{ on = "3", run = "tab_switch 2", desc = "Switch to third tab" },
	{ on = "4", run = "tab_switch 3", desc = "Switch to fourth tab" },
	{ on = "5", run = "tab_switch 4", desc = "Switch to fifth tab" },
	{ on = "6", run = "tab_switch 5", desc = "Switch to sixth tab" },
	{ on = "7", run = "tab_switch 6", desc = "Switch to seventh tab" },
	{ on = "8", run = "tab_switch 7", desc = "Switch to eighth tab" },
	{ on = "9", run = "tab_switch 8", desc = "Switch to ninth tab" },

	# Tasks
	{ on = "w", run = "tasks:show", desc = "Show task manager" },

	# Help
	{ on = "<F1>", run = "help", desc = "Open help" },
]

[tasks]

keymap = [
	{ on = "<Esc>", run = "close", desc = "Close task manager" },

	{ on = "k", run = "arrow prev", desc = "Previous" },
	{ on = "j", run = "arrow next", desc = "Next" },

	{ on = "<Enter>", run = "inspect", desc = "Inspect" },
	{ on = "X",       run = "cancel",  desc = "Cancel" },

	{ on = "<F1>", run = "help", desc = "Open help" },
]

[spot]

keymap = [
	{ on = "<Esc>", run = "close", desc = "Close the spot" },

	{ on = "k", run = "arrow prev", desc = "Previous line" },
	{ on = "j", run = "arrow next", desc = "Next line" },
	{ on = "h", run = "swipe prev", desc = "Swipe to previous file" },
	{ on = "l", run = "swipe next", desc = "Swipe to next file" },

	{ on = [ "c", "c" ], run = "copy cell", desc = "Copy selected cell" },

	{ on = "<F1>", run = "help", desc = "Open help" },
]

[pick]

keymap = [
	{ on = "<Esc>",   run = "close",          desc = "Cancel pick" },
	{ on = "<C-[>",   run = "close",          desc = "Cancel pick" },
	{ on = "<C-c>",   run = "close",          desc = "Cancel pick" },
	{ on = "<Enter>", run = "close --submit", desc = "Submit the pick" },

	{ on = "k", run = "arrow prev", desc = "Previous option" },
	{ on = "j", run = "arrow next", desc = "Next option" },

	{ on = "<F1>", run = "help", desc = "Open help" },
]

[input]

keymap = [
	{ on = "<Enter>", run = "close --submit", desc = "Submit input" },
	{ on = "<Esc>",   run = "escape",         desc = "Back to normal mode, or cancel input" },

	# Mode
	{ on = "i", run = "insert",                          desc = "Enter insert mode" },
	{ on = "I", run = [ "move first-char", "insert" ],   desc = "Move to the BOL, and enter insert mode" },
	{ on = "a", run = "insert --append",                 desc = "Enter append mode" },
	{ on = "A", run = [ "move eol", "insert --append" ], desc = "Move to the EOL, and enter append mode" },
	{ on = "v", run = "visual",                          desc = "Enter visual mode" },

	# Character-wise movement
	{ on = "h",       run = "move -1", desc = "Move back a character" },
	{ on = "l",       run = "move 1",  desc = "Move forward a character" },
	{ on = "<Left>",  run = "move -1", desc = "Move back a character" },
	{ on = "<Right>", run = "move 1",  desc = "Move forward a character" },

	# Word-wise movement
	{ on = "b",         run = "backward",                    desc = "Move back to the start of the current or previous word" },
	{ on = "w",         run = "forward",                     desc = "Move forward to the start of the next word" },
	{ on = "e",         run = "forward --end-of-word",       desc = "Move forward to the end of the current or next word" },

	# Line-wise movement
	{ on = "0",      run = "move bol",        desc = "Move to BOL" },
	{ on = "$",      run = "move eol",        desc = "Move to EOL" },

	# Delete
	{ on = "<Backspace>", run = "backspace",         desc = "Delete the character before the cursor" },
	{ on = "<Delete>",    run = "backspace --under", desc = "Delete the character under the cursor" },

	# Paste/Kill
	{ on = "D", run = [ "delete", "move eol" ],                      desc = "Cut until EOL" },
	{ on = "s", run = [ "delete --insert", "move 1" ],               desc = "Cut current character, and enter insert mode" },
	{ on = "x", run = [ "delete", "move 1 --in-operating" ],         desc = "Cut current character" },
	{ on = "y", run = "yank",                                              desc = "Copy selected characters" },
	{ on = "p", run = "paste",                                             desc = "Paste copied characters after the cursor" },

	# Undo/Redo/Casefy
	{ on = "u",     run = [ "undo", "casefy lower" ], desc = "Undo, or lowercase if in visual mode" },
	{ on = "U",     run = [ "redo", "casefy upper" ],             desc = "Uppercase" },

	{ on = "<F1>", run = "help", desc = "Open help" },
]

[confirm]

keymap = [
	{ on = "<Esc>",   run = "close",          desc = "Cancel the confirm" },
	{ on = "<Enter>", run = "close --submit", desc = "Submit the confirm" },

	{ on = "n", run = "close",          desc = "Cancel the confirm" },
	{ on = "y", run = "close --submit", desc = "Submit the confirm" },

	{ on = "k", run = "arrow prev", desc = "Previous line" },
	{ on = "j", run = "arrow next", desc = "Next line" },

	{ on = "<Up>",   run = "arrow prev", desc = "Previous line" },
	{ on = "<Down>", run = "arrow next", desc = "Next line" },

	{ on = "<F1>", run = "help", desc = "Open help" },
]

[cmp]

keymap = [
	{ on = "<C-c>",   run = "close",                                      desc = "Cancel completion" },
	{ on = "<Tab>",   run = "close --submit",                             desc = "Submit the completion" },
	{ on = "<Enter>", run = [ "close --submit", "input:close --submit" ], desc = "Complete and submit the input" },

	{ on = "<Up>",   run = "arrow prev", desc = "Previous item" },
	{ on = "<Down>", run = "arrow next", desc = "Next item" },

	{ on = "<F1>", run = "help", desc = "Open help" },
]

[help]

keymap = [
	{ on = "<Esc>", run = "escape", desc = "Clear the filter, or hide the help" },
	{ on = "<C-c>", run = "close",  desc = "Hide the help" },

	{ on = "k", run = "arrow prev", desc = "Previous line" },
	{ on = "j", run = "arrow next", desc = "Next line" },

	{ on = "f", run = "filter", desc = "Filter help items" },
]
