[mgr]
mouse_events   = [ "click", "scroll", "touch" ]

[preview]
wrap            = "no"

[opener]
edit = [
	{ run = "xdg-open %s1", desc = "$EDITOR",      for = "unix", block = true },
]
play = [
	{ run = "xdg-open %s1",                desc = "Play", for = "linux" },
]
open = [
	{ run = "xdg-open %s1",    desc = "Open", for = "linux" },
]
reveal = [
	{ run = "xdg-open %d1",         desc = "Reveal", for = "linux" },
]
extract = [
	{ run = "ya pub extract --list %s", desc = "Extract here" },
]
